### ISSUE TITLE
Issue with Laravel 5.3 and update?

### ISSUE THREAD

**Issue by torkiljohnsen** [vinkla/laravel-translator#65]
Seems like this is not working with Laravel 5.3:

`$article->update(['title' => 'Whoa. This is heavy.']);`

This is because Laravel changed their `Eloquent\Model->save` method. In 5.2 it was this:

```php
if ($this->exists) {
    $saved = $this->performUpdate($query, $options);
} else {
    $saved = $this->performInsert($query, $options);
}

if ($saved) {
    $this->finishSave($options);
}
```

The call to `finishSave` is what triggers the saving of the translations.

Now, it looks like this. With the new `isDirty`-check, which will return false since the `$article` model itself has not been updated, just the translation:

```php
if ($this->exists) {
    $saved = $this->isDirty() ? $this->performUpdate($query) : false;
} else {
    $saved = $this->performInsert($query);
}

if ($saved) {
    $this->finishSave($options);
}
```

As a consequence, translations are not being saved, because `finishSave` is never called.

**Comment by vinkla** [comment]
Thanks for reporting! Maybe we need to override the `save` method in order to make it work in our scenario. Do you feel up for a pull request? It would be awesome if you would.

**Comment by torkiljohnsen** [comment]
Looking into it. Either overriding `save()` or perhaps overriding the `isDirty()` method? That would ensure that behavior stays the same and `performUpdate` is called too, like before.

Another option I can think of is handling translations via Eloquent events instead. Have you considered that?

**Comment by torkiljohnsen** [comment]
Also another side effect of 5.3: Previously `save` would return `true` when updating only translated attributes, now it returns false. Overriding `isDirty` is the best option going forward if we want to prevent this I think. 

It makes sense that `save` returns `true` even if only a translation was updated, don't you think?

**Comment by vinkla** [comment]
TBH, I haven't tried this package with Laravel 5.3 except for the unit tests. Any pull request you send my way would be appreciated!

> Overriding isDirty is the best option going forward if we want to prevent this I think.

I totally agree with you. The docbloc for `isDirty()` describes it like this:

> Determine if the model or given attribute(s) have been modified.

Which makes sense to override this method.

> It makes sense that save returns true even if only a translation was updated, don't you think?

Yeah, I agree.

**Comment by torkiljohnsen** [comment]
One of your forks solved it like this: https://github.com/joturako/translator/commit/3ec3f8fd05a2f32c2bdceae678546dae70bf9934

**Comment by vinkla** [comment]
Yeah, could be a solution. Though, what happens if someone wants to override the `boot()` method? Then the `boot()` method on our trait is replaced right?

**Comment by torkiljohnsen** [comment]
Yep. I need some help getting this set up to run the test suite before I can make any commits…

**Comment by torkiljohnsen** [comment]
I forked here, with branch name `laravel-5.3`:
https://github.com/torkiljohnsen/laravel-translator/tree/laravel-5.3

Created a new Laravel project and added this to my `composer.json`:

```js
"repositories": [
    {
        "type": "path",
        "url": "https://github.com/torkiljohnsen/laravel-translator"
    }
],
```

Then I added this to `require-dev`:
```js
```

**Comment by torkiljohnsen** [comment]
… ah… I used `path` instead of `vcs` … :P

**Comment by torkiljohnsen** [comment]
True.

**Comment by torkiljohnsen** [comment]
Could you give some pointers as to how to get the test suite up and running? I got a Laravel install with vinkla/translator up and running now from my own fork, but having trouble running the test suite.

Tried `phpunit vendor/vinkla/translator/tests` but test classes are perhaps not autoloaded and `AbstractTestCase` can't be found.

**Comment by vinkla** [comment]
Yeah, there seems to be some issues with the current tests. I guess it has to do with the 5.3 upgrade. I'll look into why the tests fail. Then you can pull that down and add your changes.

**Comment by torkiljohnsen** [comment]
Any news @vinkla ?

**Comment by vinkla** [comment]
@torkiljohnsen sorry, I've been really bussy these last couple of days. Will look into it soon.

**Comment by torkiljohnsen** [comment]
![help me help you](https://cloud.githubusercontent.com/assets/318089/18162933/cf2384f2-7038-11e6-8f10-7b0c3f1742e5.gif)

**Comment by vinkla** [comment]
I've fixed the migrations issue in 55a45af0b06204ab7f175532d8c93f387b4170a1. The tests still fail but this is because of the bug we've discussed here.

**Comment by vinkla** [comment]
I've pushed a fix for this in 7c077968d7516196aadbc46c9f1c034794105849. Thanks for pointing the issue out!

**Comment by vinkla** [comment]
Could you maybe try it out?

**Comment by vinkla** [comment]
@torkiljohnsen could you maybe try it out?
