### ISSUE TITLE
updateTimestamps in Eloquent/Model fails with latest isDirty

### ISSUE THREAD

**Issue by torkiljohnsen** [vinkla/laravel-translator#67]
The pull request #66 created an issue.

With the latest PR, `isDirty` will now return true for the tests in `Model->updateTimestamps`. This will prevent `Model` from setting timestamps when creating new models. Not good.

**Comment by vinkla** [comment]
Good catch! Maybe you could submit a pull request to fix this?

**Comment by torkiljohnsen** [comment]
Not sure what would be the best approach here… Overriding `isDirty()` could have unexpected consequences in other places of the framework, and also with other packages.

**Comment by vinkla** [comment]
Yeah, true.

**Comment by torkiljohnsen** [comment]
Hooking into the `saved` event of the parent model is not necessarily the best approach either. If a model update is done, but the core model itself is not changed, only it's translation, then the `saved` event will not be triggered since `performUpdate` will not run.

**Comment by vinkla** [comment]
I've pushed a fix in a749482cb1be65e990854c084f87a5554c2bca02. Do you think you could test again?

**Comment by torkiljohnsen** [comment]
Seems to be working fine in my tests! 👍

**Comment by vinkla** [comment]
@torkiljohnsen great! Then we only have the Travis tests to fix.
