### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by torkiljohnsen** [vinkla/laravel-translator#69]
Have you tried this with Lumen?

I think it should work for the most part. The facades usage in Translatable.php might pose a problem, since facades are disabled by default in Lumen 5.2+.

I think you can convert it pretty easily though, to not use facades:
- The setLocale/getLocale methods seem to be used for adding data to the cache. Perhaps `getEmptyTranslation()` can pass on `$locale` to `setAttribute()` as a parameter instead? That way you can possibly get rid of `App::` calls in the code.
- Calls to `Config::get` can be replaced with `config()`. This works in both [Laravel](https://laravel.com/docs/5.3/configuration#accessing-configuration-values) and [Lumen](https://lumen.laravel.com/docs/5.2/configuration#accessing-configuration-values).

Lumen can be configured to run _with_ facades too of course, but it's faster without.

**Comment by vinkla** [comment]
I wouldn't recommend using this package with Lumen. I haven't tried it myself. Also we should try to avoid using facades and helper methods in third party packages. 

Tell me about your use case.

**Comment by torkiljohnsen** [comment]
I think your package is a nice addition to any translatable API endpoint, thus making it a good choice for both Lumen and Laravel users :)

The package dependencies are a bit unclear though. It is clearly dependent on Illuminate/Database(/Eloquent), since it's calling `getDirty()`, Illuminate/Foundation (it is using Application) and Illuminate/Config. The Laravel or Lumen requirement is clear. 

As far as dependencies go, I would say it is an advantage to keep the contact surface between your component and the framework as small as possible, so using Facades ([in the pattern sense](https://en.wikipedia.org/wiki/Facade_pattern)) is good. The global helper methods will just make your application compliant with both Laravel and Lumen, and changes nothing regarding dependencies IMO.

And us purists may detest and try to avoid these global helper methods as much as we want, but the fact remains that for instance calling `config()` is the recommended method in both the official  [Lumen](https://lumen.laravel.com/docs/5.3/configuration) and [Laravel](https://laravel.com/docs/5.3/configuration) documentation. Using it will coincidentally also make your package compliant with both frameworks, out of the box.

**Comment by vinkla** [comment]
I'm glad you took the time to write such a thorough answer. You make a good point. Any pull request you send my way I will happily take a look at!

**Comment by torkiljohnsen** [comment]
I tested this today and could pretty much get it to work in Lumen.

In the Translatable trait, however, I had to replace:
 `App::getLocale();` with `app('translator')->getLocale;`, and 
`App::setLocale($locale);` with `app('translator')->setLocale($locale);`.

Just some simple tests so far, but it looks good so far.

**Comment by vinkla** [comment]
Okay, cool. I'm not sure how I feel about using helper methods in a third-party package though...

Isn't there some way to solve this with facades or with a Laravel service provider?

**Comment by torkiljohnsen** [comment]
Sure. `App::make('translator')->getLocale()`;

**Comment by torkiljohnsen** [comment]
Of course, Laravel's `Application` class also updates the config and fires an event:

```php
    public function setLocale($locale)
    {
        $this['config']->set('app.locale', $locale);
        $this['translator']->setLocale($locale);
        $this['events']->fire('locale.changed', [$locale]);
    }
```

**Comment by vinkla** [comment]
I've now managed to get everything to work properly with Travis. Did you get further on this?

**Comment by torkiljohnsen** [comment]
Yes, I made it work with the above changes, but only within the acceptance tests' scope of my app though. I did not run through the whole test suite for laravel-translator.

Difference between Lumen and Laravel is that **in Laravel** you call `Application->setLocale()`. This does three things:
 1. Set config `app.locale`
 2. set Locale on the translator
 3. Fire the `locale.changed` event

**In Lumen** though, you would call the translator directly with `app('translator')->setLocale()` or `App::make('translator')->setLocale()`, so the difference here is that the config variable will not be set automatically and the `locale.changed` event will not be fired.

**Comment by vinkla** [comment]
> …so the difference here is that the config variable will not be set automatically and the locale.changed event will not be fired.

Are there any downsides of this that we haven't thought of?

**Comment by vinkla** [comment]
Any update?

**Comment by torkiljohnsen** [comment]
I have no more updates, no? I think it should work fine with Lumen support built in, but that is not something I am actively working on these days.

**Comment by torkiljohnsen** [comment]
@vinkla Tagging a new release would be good btw. My project has been on `dev-master` for god knows how long now :)

**Comment by vinkla** [comment]
I'll try to tag a release today. Do you know if it even works with Lumen today?

**Comment by torkiljohnsen** [comment]
It needs the mentioned changes to setLocale and getLocale

**Comment by vinkla** [comment]
Okay, lets skip Lumen for now and then we can discuss it in the future.

**Comment by vinkla** [comment]
Version 4.0.0 is now released. Thanks for helping out!
