### ISSUE TITLE
translate method not always returning a Model instance

### ISSUE THREAD

**Issue by schelmo** [vinkla/laravel-translator#73]
For me the translate method sometimes returns null.
It happens when your translated model have no translation yet.

for example:
```php
$article = Article::create(['thumbnail' => 'http://i.imgur.com/tyfwfEX.jpg']);
echo $article->title;
```
gives me:
> Type error: Return value of Article::translate() must be an instance of Illuminate\Database\Eloquent\Model, null returned

can we simply remove the return type declaration of the translate method ?

**Comment by vinkla** [comment]
Did you add the `$translatables` array to you eloquent model?

**Comment by schelmo** [comment]
yes sure.

a possible testcase for that, which fails:
```php
    public function testEmptyTranslation ()
    {
        $article = Article::create(['thumbnail' => 'http://i.imgur.com/tyfwfEX.jpg']);
        $this->assertNull($article->title);
    }
```

**Comment by vinkla** [comment]
Thanks for reporting it. Fixed in https://github.com/vinkla/laravel-translator/releases/tag/4.2.2
