### ISSUE TITLE
Insert multiple translation data

### ISSUE THREAD

**Issue by vanrijs** [vinkla/laravel-translator#79]
Hi!

What is the best way to create/update multiple translations?

I found this:
```
        $subscription->translations()->update([
            ['locale' => 'en', 'name' => 'This is english'],
            ['locale' => 'nl', 'name' => 'Detta är svenska'],
        ]);
```

But then i get this error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'field list' (SQL: update `subscription_translations` set `0` = en, `1` = nl, `updated_at` = 2017-11-26 15:07:28 where `subscription_translations`.`subscription_id` = 1 and `subscription_translations`.`subscription_id` is not null)`

**Comment by vinkla** [comment]
If you update multiple rows at once you need to pass the ID for each translation. Your example should work if you use `create` instead of `updated`.
