### ISSUE TITLE
Overriding finishSave is not necessarily a good thing

### ISSUE THREAD

**Issue by torkiljohnsen** [vinkla/laravel-translator#81]
Overriding the core `finishSave` does not seem ideal to me. I am in a situation where multiple things happen when the save of a translated model happens, and these things now come into conflict with one another.

It would be better if the translatable trait would listen for events like `created` and `updated`, and save translations after those. That way you would still have translations ready when `saving` and `saved` is fired on the model too, so you can tap into a larger part of the request lifecycle. Right now, you have to wait for the `saved` event before any translations are updated/created.

**Comment by vinkla** [comment]
That sounds like a good idea @torkiljohnsen! I've added you as a collaborator to the repository since you're active contributor and user of the project. You can now add custom branches to the project. Everything still needs to go through pull requests and tests must pass. I promise to look at any pull request you send my way!

**Comment by torkiljohnsen** [comment]
Here you go! 🙂

**Comment by vinkla** [comment]
> It would be better if the translatable trait would listen for events like `created` and `updated`, and save translations after those. That way you would still have translations ready when `saving` and `saved` is fired on the model too, so you can tap into a larger part of the request lifecycle. Right now, you have to wait for the `saved` event before any translations are updated/created.

Since `saved` is trigged right after `created` and `updated` what are the benefits of replacing `saved`? Do you've an example use-case?

**Comment by torkiljohnsen** [comment]
I had another package that was also overriding the core `finishSave` method, so they came into conflict with one another. That is why I made the PR.

If we tap into `created` and `updating`, we can do other stuff when `saved` is triggered while safely assuming that translations will be available.

Another benefit is that for instance on `created` the translation does not exist and will have to be created, so you can `getEmpty` and/or `create` directly, without any `if/else`.

**Comment by vinkla** [comment]
I see. Since two traits can't share the same method name your solution in #82 is the way to go. I'll close this in favour of the pull request.
